services:
  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    image: raulhr16/backend:12
    container_name: backend-app
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "3000:3000"

  frontend:
    image: raulhr16/frontend:12
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
